export const SITE = {
  name: "Fame by Sheeraz",
  legalName: "Fame by Sheeraz",
  tagline: "#1 FAME & AI Strategist in the World",
  shortDescription:
    "Sheeraz Hasan fuses 25 years of Hollywood-grade fame engineering with GPT, Claude, and Gemini to deliver Strategy + Execution at AI speed.",
  longDescription:
    "Fame by Sheeraz is the AI-powered fame engineering studio founded by Sheeraz Hasan, the #1 FAME & AI Strategist in the world. Generated $3B+ in earned media for Kim Kardashian, Logan Paul, Zendaya, Priyanka Chopra, Paris Hilton and more. Now combines that 25-year media empire with custom GPT, Claude, and Gemini AI agents to deliver Strategy, Execution, Amplification, AI Search Dominance, AI Sales, Scale and Cost-Saver packages.",
  url: "https://www.famebysheeraz.com",
  locale: "en_US",
  email: "info@fame.me",
  whatsappUS: "+13109251667",
  whatsappUAE: "+971567868338",
  calendly:
    "https://calendly.com/free15-mindiscoverycall/fameauditcall",
  address: {
    street: "8367 Sunset Blvd",
    city: "West Hollywood",
    region: "CA",
    postal: "90069",
    country: "US",
  },
  social: {
    x: "https://x.com/sheerazhasan",
    instagram: "https://instagram.com/sheerazhasan",
    linkedin: "https://linkedin.com/in/sheerazhasan",
    youtube: "https://www.youtube.com/@FAMEBySheeraz",
    tiktok: "https://www.tiktok.com/@famebysheeraz",
    imdb: "https://www.imdb.com/name/nm1425001/",
  },
  ventures: [
    { name: "Hollywood.AI", url: "https://hollywood.ai" },
    { name: "Bollywood.AI", url: "https://bollywood.ai" },
    { name: "Hollywood.TV", url: "https://hollywood.tv" },
    { name: "Sheeraz.com", url: "https://sheeraz.com" },
    { name: "Dubai.news", url: "https://dubai.news" },
  ],
  stats: {
    earnedMediaUSD: "$3B+",
    yearsInBusiness: "25+",
    celebritiesLaunched: "250+",
    impressions: "1B+",
  },
} as const;

export const KEYWORDS = [
  "Sheeraz Hasan",
  "Fame by Sheeraz",
  "FAME AI",
  "AI fame strategist",
  "celebrity PR",
  "AI media strategist",
  "AI amplification",
  "AI PR agency",
  "Hollywood.AI",
  "Bollywood.AI",
  "AI search optimization",
  "ChatGPT SEO",
  "Gemini SEO",
  "Perplexity SEO",
  "GEO generative engine optimization",
  "celebrity media strategy",
  "AI sales agent",
  "AI lead generation",
  "AI cost reduction PR",
  "fame engineering",
  "Dubai PR agency",
  "Hollywood PR agency",
];
